version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bae           # Contraseña root personalizada
      MYSQL_DATABASE: bae       # Nombre de la base de datos
      MYSQL_USER: bae                    # Usuario normal
      MYSQL_PASSWORD: bae                # Contraseña del usuario normal
    volumes:
      - mysql_data:/var/lib/mysql        # Persistencia de datos en volumen nombrado
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3309:3306"                       # Puerto externo 3309 -> interno 3306
    networks:
      - db-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: bae
    ports:
      - "8099:80"
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
